
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ipd11
 */
public class PeapleLis extends javax.swing.JFrame {
    DefaultListModel<Person>peopleListModel = new DefaultListModel<>();
    
    /**
     * Creates new form PeapleLis
     */
    public PeapleLis() {
         try {
            StringBuilder warnings = new StringBuilder();
            ArrayList<Person> list = PeapleFilleAccess.loadPersonListFromFile(warnings);
            for (Person p : list) {
                peopleListModel.addElement(p);
            }
            // show warnings if any
            if (warnings.length() > 0) {
                JOptionPane.showMessageDialog(this,
                    warnings.toString(),
                    "Problems during data reading from file",
                    JOptionPane.WARNING_MESSAGE);
            }
        }catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Data file reading error",
                    JOptionPane.ERROR_MESSAGE);
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        pmiDelete = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        lspeople = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfAge = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        lblIndex = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfPostalcod = new javax.swing.JTextField();
        btStorByName = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jMenu1.setText("Menu");

        pmiDelete.setText("dealet");
        pmiDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmiDeleteActionPerformed(evt);
            }
        });
        jMenu1.add(pmiDelete);

        popupMenu.add(jMenu1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lspeople.setModel(peopleListModel);
        lspeople.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lspeopleMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lspeopleMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(lspeople);

        jLabel1.setText("Id");

        jLabel2.setText("Name");

        jLabel3.setText("Age");

        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btUpdate.setText("Update");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        lblIndex.setText("-");

        jLabel4.setText("postalcod");

        btStorByName.setText("By Name");
        btStorByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStorByNameActionPerformed(evt);
            }
        });

        jButton2.setText("By Age");

        jButton3.setText("By Pc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btStorByName)
                        .addGap(3, 3, 3)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btUpdate)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfPostalcod))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel3)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfAge)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 2, Short.MAX_VALUE))
                                    .addComponent(tfName))))
                        .addGap(19, 19, 19))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblIndex)
                    .addComponent(btStorByName)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfPostalcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAdd)
                            .addComponent(btUpdate))
                        .addGap(0, 91, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
    try{
      String name =tfName.getText();
      String ageStr = tfAge.getText();
      String postalCode = tfPostalcod.getText();
      // fix peson may fail and trow an errore
      int age = Integer.parseInt(ageStr);
      Person p = new Person(name,age,postalCode);
      p.setName(name);
      p.setAge(age);
      p.setPostalCode(postalCode);
      peopleListModel.addElement(p);
    }catch(NumberFormatException ex){
     JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "numvur format errore",
                    JOptionPane.ERROR_MESSAGE);
    }catch(IllegalArgumentException ex){
     JOptionPane.showMessageDialog(this,
                     ex.getMessage(),
                    "input data errore",
                    JOptionPane.ERROR_MESSAGE);

    }
    }//GEN-LAST:event_btAddActionPerformed

    int currIndex = -1;
    private void lspeopleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lspeopleMouseClicked
       currIndex= lspeople.getSelectedIndex();
        if(currIndex ==-1){
        lblIndex.setText("-");
        return;
        }
        Person p = peopleListModel.elementAt(currIndex);
        lblIndex.setText(currIndex + "");
        tfName.setText(p.getName());
        tfAge.setText(p.getAge()+"");
        tfPostalcod.setText(p.getPostalcode());
    }//GEN-LAST:event_lspeopleMouseClicked

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        if (currIndex == -1){
        return;
        }
        try{
      String name =tfName.getText();
      String ageStr = tfAge.getText();
      String postalCode = tfPostalcod.getText();
      // fix peson may fail and trow an errore
      int age = Integer.parseInt(ageStr);
      Person p = new Person(name,age,postalCode);
      p.setName(name);
      p.setAge(age);
      p.setPostalCode(postalCode);
      peopleListModel.setElementAt(p, currIndex);
    }catch(NumberFormatException ex){
     JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "numvur format errore",
                    JOptionPane.ERROR_MESSAGE);
    }catch(IllegalArgumentException ex){
     JOptionPane.showMessageDialog(this,
                     ex.getMessage(),
                    "input data errore",
                    JOptionPane.ERROR_MESSAGE);

    }
    }//GEN-LAST:event_btUpdateActionPerformed


    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      try {
            ArrayList<Person> list = new ArrayList<>();
            for (int i = 0; i < peopleListModel.size(); i++) {
                list.add(peopleListModel.get(i));
            }
            PeapleFilleAccess.savePersonListToFile(list);
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "File writing error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void lspeopleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lspeopleMouseReleased
        if (evt.getButton() == 3) { // right button
            currIndex = lspeople.locationToIndex(evt.getPoint());
            //System.out.println("Index: " + index);
            if (currIndex != -1) {
                lspeople.setSelectedIndex(currIndex); //select the item
                popupMenu.show(lspeople, evt.getX(), evt.getY()); //and show the menu
            }
        }
    }//GEN-LAST:event_lspeopleMouseReleased

    private void pmiDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmiDeleteActionPerformed
        System.out.println("Delete selected");
        if (currIndex == -1) {
            return;
        }
        Person p = peopleListModel.get(currIndex);
        int choice = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete this item?\n" + p.toString(),
                "Confirm delete",
                JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            peopleListModel.remove(currIndex);
        }
    }//GEN-LAST:event_pmiDeleteActionPerformed

    private void btStorByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStorByNameActionPerformed
        try {
            StringBuilder warnings = new StringBuilder();
            ArrayList<Person> list = PeapleFilleAccess.loadPersonListFromFile(warnings);
            // TODO: sort here
            peopleListModel.clear();
            for (Person p : list) {
                peopleListModel.addElement(p);
            }
            if (warnings.length() > 0) {
                JOptionPane.showMessageDialog(this,
                        warnings.toString(),
                        "Problems during data reading from file",
                        JOptionPane.WARNING_MESSAGE);
            }
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Data file reading error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btStorByNameActionPerformed

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeapleLis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeapleLis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeapleLis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeapleLis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeapleLis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btStorByName;
    private javax.swing.JButton btUpdate;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIndex;
    private javax.swing.JList<Person> lspeople;
    private javax.swing.JMenuItem pmiDelete;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPostalcod;
    // End of variables declaration//GEN-END:variables
}
